server:
    port: 8080

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost/SSAFY_PJT1?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
        username: root
        password: ssafy

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: a43727702
        password: '!qotjrdyd1'
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    auth: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: ae3417f23d74a47e083cca850c4ecf08
                        client-secret: Rj5lUxyDdKMum72rNl0xTb2iRSIqWWo6
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:3000/kakaoLogin
                        client-name: Kakao
                        scope: profile,
                            account_email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user_name_atrribute: id
jwt:
    header: Authorization
    #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
    #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400 # 토큰 만료 시간

logging:
    level:
        me.silvernine: DEBUG
